http:

  middlewares:
  
    CbetMiddleware:
      stripPrefix:
        prefixes:
          - "/demo"
        forceSlash: false
        
    SecHeaders:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true

        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
