http:
  routers:
    routercbet:
      entryPoints: web
      rule: Host("cbet.training01.continuous.team")
      service: servicecbet
      priority: 2
      
    routerrbet:
      entryPoints: web
      rule: Host("rbet.training01.continuous.team")
      service: servicerbet
      priority: 2
      
  services:
    servicecbet:
      loadBalancer:
        servers:
          - url: http://10.10.1.36

    servicerbet:
      loadBalancer:
        servers:
          - url: http://10.10.1.36:8080
    
    