http:
  routers:
    router_cbet_path:
      entryPoints: 
        - web
      rule: "Host(`cbet.training01.continuous.team`) && PathPrefix(`/demo`)"
      service: servicecbet
      priority: 40
      middlewares:
        - CbetMiddleware
  
    routercbet:
      entryPoints: 
        - web
      rule: Host("cbet.training01.continuous.team")
      service: servicecbet
      priority: 20
      
    routerrbet:
      entryPoints: 
       - web
      rule: Host("rbet.training01.continuous.team")
      service: servicerbet
      priority: 20
      
  services:
    servicecbet:
      loadBalancer:
        servers:
          - url: http://10.10.1.36

    servicerbet:
      loadBalancer:
        servers:
          - url: http://10.10.1.36:8080
    
    